<?php

return [
    'catalog' => [
        'doctor' => [
            'label' => 'Doctor profile dashboard',
            'description' => 'Access to the doctor profile and dashboard.',
        ],
        'profile_basic' => [
            'label' => 'Basic profile page',
            'description' => 'Public doctor profile with essential information.',
        ],
        'profile_professional' => [
            'label' => 'Professional profile page',
            'description' => 'Enhanced public profile sections and presentation.',
        ],
        'appointments' => [
            'label' => 'Appointment dashboard',
            'description' => 'View appointment lists, details, and calendar screens.',
        ],
        'appointment_booking' => [
            'label' => 'Online appointment booking',
            'description' => 'Allow patients to submit new appointments.',
        ],
        'appointment_management' => [
            'label' => 'Appointment management',
            'description' => 'Confirm, reschedule, and manage appointment status.',
        ],
        'subdomain' => [
            'label' => 'Subdomain',
            'description' => 'Use a platform subdomain.',
        ],
        'custom_domain' => [
            'label' => 'Custom domain',
            'description' => 'Use a registered or existing custom domain.',
        ],
        'premium_ssl' => [
            'label' => 'Premium SSL',
            'description' => 'Premium SSL setup for custom domains.',
        ],
        'template_basic' => [
            'label' => 'Basic template',
            'description' => 'Access to the basic profile template.',
        ],
        'themes_multiple' => [
            'label' => 'Multiple themes',
            'description' => 'Access professional or multiple public themes.',
        ],
        'analytics_basic' => [
            'label' => 'Basic analytics',
            'description' => 'Basic profile and visit metrics.',
        ],
        'analytics_advanced' => [
            'label' => 'Advanced analytics',
            'description' => 'Advanced reporting and booking analytics.',
        ],
        'basic_meta_tags' => [
            'label' => 'Basic meta tags',
            'description' => 'Basic title and description meta tags.',
        ],
        'advanced_seo' => [
            'label' => 'Advanced SEO suite',
            'description' => 'Advanced SEO fields and optimization tools.',
        ],
        'managed_seo' => [
            'label' => 'Managed SEO and local ranking',
            'description' => 'Managed SEO and local ranking support.',
        ],
        'email_support' => [
            'label' => 'Community/email support',
            'description' => 'Community or email support.',
        ],
        'priority_email_support' => [
            'label' => 'Priority email support',
            'description' => 'Priority support through email.',
        ],
        'phone_support' => [
            'label' => '24/7 phone support',
            'description' => 'Phone support for premium customers.',
        ],
        'email_notifications' => [
            'label' => 'Email notifications',
            'description' => 'Email notifications for appointments and workflow events.',
        ],
        'sms_reminders' => [
            'label' => 'SMS reminders',
            'description' => 'SMS reminders for appointments.',
        ],
        'patients' => [
            'label' => 'Patient management',
            'description' => 'Patient profiles, records, and history.',
        ],
        'online_payments' => [
            'label' => 'Online payment integration',
            'description' => 'Accept online payments for appointments and services.',
        ],
        'branding_css' => [
            'label' => 'Advanced branding and custom CSS',
            'description' => 'Custom CSS and advanced brand controls.',
        ],
        'services' => [
            'label' => 'Services and chambers',
            'description' => 'Chambers, services, telemedicine, and billing sections.',
        ],
        'content' => [
            'label' => 'Content tools',
            'description' => 'Posts, testimonials, FAQs, and AI content tools.',
        ],
    ],

    'presets' => [
        'free' => [
            'doctor' => true,
            'profile_basic' => true,
            'profile_professional' => false,
            'appointments' => true,
            'appointment_booking' => false,
            'appointment_management' => false,
            'subdomain' => true,
            'custom_domain' => false,
            'premium_ssl' => false,
            'template_basic' => true,
            'themes_multiple' => false,
            'analytics_basic' => true,
            'analytics_advanced' => false,
            'basic_meta_tags' => true,
            'advanced_seo' => false,
            'managed_seo' => false,
            'email_support' => true,
            'priority_email_support' => false,
            'phone_support' => false,
            'email_notifications' => false,
            'sms_reminders' => false,
            'patients' => false,
            'online_payments' => false,
            'branding_css' => false,
            'services' => true,
            'content' => false,
        ],
        'standard' => [
            'doctor' => true,
            'profile_basic' => true,
            'profile_professional' => true,
            'appointments' => true,
            'appointment_booking' => true,
            'appointment_management' => true,
            'subdomain' => true,
            'custom_domain' => true,
            'premium_ssl' => false,
            'template_basic' => true,
            'themes_multiple' => true,
            'analytics_basic' => true,
            'analytics_advanced' => true,
            'basic_meta_tags' => true,
            'advanced_seo' => true,
            'managed_seo' => false,
            'email_support' => true,
            'priority_email_support' => true,
            'phone_support' => false,
            'email_notifications' => true,
            'sms_reminders' => false,
            'patients' => true,
            'online_payments' => true,
            'branding_css' => false,
            'services' => true,
            'content' => true,
        ],
        'premium' => [
            'doctor' => true,
            'profile_basic' => true,
            'profile_professional' => true,
            'appointments' => true,
            'appointment_booking' => true,
            'appointment_management' => true,
            'subdomain' => true,
            'custom_domain' => true,
            'premium_ssl' => true,
            'template_basic' => true,
            'themes_multiple' => true,
            'analytics_basic' => true,
            'analytics_advanced' => true,
            'basic_meta_tags' => true,
            'advanced_seo' => true,
            'managed_seo' => true,
            'email_support' => true,
            'priority_email_support' => true,
            'phone_support' => true,
            'email_notifications' => true,
            'sms_reminders' => true,
            'patients' => true,
            'online_payments' => true,
            'branding_css' => true,
            'services' => true,
            'content' => true,
        ],
    ],
];
